# Generated by Django 4.2.5 on 2023-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('responsavel', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=7)),
                ('valor', models.IntegerField(max_length=10)),
            ],
        ),
    ]
