# Generated by Django 4.2.5 on 2023-09-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_despesas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='descricao',
            field=models.TextField(),
        ),
    ]
