# Generated by Django 4.2.5 on 2023-09-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_despesas_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('responsavel', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=7)),
                ('valor', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uptade_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Despesas',
        ),
    ]
